### ISSUE TITLE
Cannot encode watermarked stream

### ISSUE THREAD

**Issue by lamalexck** [openvinotoolkit/dlstreamer_gst#211] opened 2021-04-29 05:40 UTC
I am trying to add watermark to my h264 encoded video output with this pipeline
```
gst-launch-1.0 filesrc location=${IN_VIDEO_FILE} \
	       ! qtdemux name=demux demux.video_0 \
	       ! h264parse \
	       ! msdkh264dec ! videoconvert ! video/x-raw \
	       ! gvadetect model=$MODEL device=$DEVICE ! queue \
	       ! gvawatermark ! queue \
	       ! msdkh264enc ! video/x-h264 \
	       ! h264parse ! mp4mux \
	       ! filesink location=${OUT_VIDEO_FILE}
```
but I got these error
```
Setting pipeline to PLAYING ...
New clock: GstSystemClock
0:00:00.309059977  1510 0x55a646d44b70 ERROR default video-frame.c:168:gst_video_frame_map_id: failed to map video frame plane 0
ERROR: from element /GstPipeline:pipeline0/GstGvaWatermark:gvawatermark0: watermark has failed to draw label
Additional debug info:
/working/dlstreamer_gst/gst/elements/gvawatermark/watermark.cpp(293): draw (): /GstPipeline:pipeline0/GstGvaWatermark:gvawatermark0:
Failed to map GstBuffer to specific memory type
	Failed to map GstBuffer to system memory
```

However, if I remove the watermark, ie as below, I was able to get an output.
```
gst-launch-1.0 filesrc location=${IN_VIDEO_FILE} \
	       ! qtdemux name=demux demux.video_0 \
	       ! h264parse \
	       ! msdkh264dec ! videoconvert ! video/x-raw \
	       ! gvadetect model=$MODEL device=$DEVICE ! queue \
	       ! msdkh264enc ! video/x-h264 \
	       ! h264parse ! mp4mux \
	       ! filesink location=${OUT_VIDEO_FILE}
```
Can you help me understand why?

**Comment by mliu2020** [comment] 2021-04-30 00:11
Hi @lamalexck,

Do you have any preference to use Media SDK plugin?

By default, DL Streamer is optimized with VAAPI plugin. The error you got might be caused by the format mismatch since gvawatermark can't find the frame data in the expected position.

If you want to use the GPU for hardware decode, you can refer to benchmark example, all you need to do is to use decodebin and enable DECODE_DEVICE with GPU. On the encoder side, you can use vaapih264enc

Mark Liu

**Comment by lamalexck** [comment] 2021-04-30 18:18
Thanks for the tips Mark.

Unfortunately, while I can get decode working with GPU
```
    GST_VAAPI_ALL_DRIVERS=1
    MEMORY_TYPE='(memory:DMABuf)'

    gst-launch-1.0 filesrc location=${IN_VIDEO_FILE} \
                   ! decodebin ! video/x-raw${MEMORY_TYPE} \
                   ! gvadetect model=$MODEL device=$DEVICE ! queue \
                   ! gvafpscounter \
                   ! fakesink sync=false
```

Re-encoding by appending  vaapih264enc  to gvafpscounter has issue

```
Pipeline is PREROLLING ...
Got context from element 'vaapiencodeh264-0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
WARNING: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0: Delayed linking failed.
Additional debug info:
./grammar.y(506): gst_parse_no_more_pads (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0:
failed delayed linking some pad of GstDecodeBin named decodebin0 to some pad of GstGvaDetect named gvadetect0
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0: Internal data stream error.
Additional debug info:
qtdemux.c(6605): gst_qtdemux_loop (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstQTDemux:qtdemux0:
streaming stopped, reason not-linked (-1)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

ie, this failed
```
    GST_VAAPI_ALL_DRIVERS=1
    MEMORY_TYPE='(memory:DMABuf)'

    gst-launch-1.0 filesrc location=${IN_VIDEO_FILE} \
                   ! decodebin ! video/x-raw${MEMORY_TYPE} \
                   ! gvadetect model=$MODEL device=$DEVICE ! queue \
                   ! gvafpscounter \
                   ! vaapih264enc \
                   ! fakesink sync=false
```

**Comment by mliu2020** [comment] 2021-05-01 01:42
I got this one working but failed on change memory type:
`gst-launch-1.0 filesrc location=${IN_VIDEO_FILE} ! qtdemux name=demux demux.video_0 ! h264parse ! vaapih264dec ! vaapipostproc ! video/x-raw,format=NV12 ! gvadetect model=$MODEL ! gvawatermark ! gvafpscounter ! vaapih264enc ! h264parse ! filesink location=${OUT_VIDEO_FILE}`

Hope this helps.

Mark

**Comment by mliu2020** [comment] 2021-05-01 02:49
Hi @lamalexck 

Got some good news, the following command line works for me:
```
gst-launch-1.0 filesrc location=${IN_VIDEO_FILE} \
            ! decodebin ! video/x-raw\(memory:VASurface\) \
            ! gvadetect pre-process-backend=vaapi model=$MODEL \
            ! gvafpscounter \
            ! vaapih264enc ! h264parse \
            ! filesink location=${OUT_VIDEO_FILE}
```

Mark Liu

**Comment by lamalexck** [comment] 2021-05-03 23:01
Thanks Mark! 
Yes, it's working for me too!!

**Comment by mliu2020** [comment] 2021-05-04 01:12
Good, 

Let me know if this solves your problem and we can close it.

Mark

**Comment by mliu2020** [comment] 2021-05-07 00:16
Let me close it for now, please feel free to re-open it if you still have question or submitted a new issue for new questions.

Mark

**Closed by mliu2020** 2021-05-07 00:16 UTC
