### ISSUE TITLE
FPS decrease a lot when doing secondary inference using HDDL, even though no object is detected

### ISSUE THREAD

**Issue by nsk-lab** [openvinotoolkit/dlstreamer_gst#152] opened 2020-11-09 08:31 UTC
We benchmarked HDDL(+CPU) performance based on below sample app. 
https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/gst_launch/face_detection_and_classification
We used FP16 models, OpenVINO 2021.1 (Offline installed)
All the displayed results were OK.

Here is the performance results.
```
■ using face movie (head-pose-face-detection-female-and-male.mp4)
[FACE] detection( CPU) => 4.5FPS
[FACE] detection(HDDL) => 48FPS
[FACE] detection( CPU)+1-classification( CPU) ⇒ 4.2 FPS
[FACE] detection(HDDL)+1-classification( CPU) ⇒ 37 FPS
[FACE] detection(HDDL)+1-classification(HDDL) ⇒ 25 FPS

■ using NO-face movie (I used "videotestsrc" gstreamer element as input)
[NO-FACE] detection( CPU) => 4.5FPS
[NO-FACE] detection(HDDL) => 48FPS
[NO-FACE] detection( CPU)+1-classification( CPU) ⇒ 4.5 FPS
[NO-FACE] detection(HDDL)+1-classification( CPU) ⇒ 48 FPS
[NO-FACE] detection(HDDL)+1-classification(HDDL) ⇒ 25 FPS
```

As you can see,
**FPS decrease a lot when doing secondary inference using HDDL, even though there are no faces in the input.**
25FPS is slower than if you did the secondary on the CPU!
```
[NO-FACE] detection(HDDL) => 48FPS
[NO-FACE] detection(HDDL)+1-classification(HDDL) ⇒ 25 FPS
```
Also, the 25FPS is same as the case when I input face-movie (and secondary inferences are conducted)
```
[FACE] detection(HDDL)+1-classification(HDDL) ⇒ 25 FPS
```

There seems to be a very large bottleneck in the HDDL for secondary inference, other than the inference time itself.
Is this the expected behavior?

**Comment by Andruxin52rus** [comment] 2020-11-16 08:28
Hi @nsk-lab ! Thanks for posting this question. Could you please share your HW setup info?  
I can see, that this sample contains `gvawatermark`, which renders analytics results on top of video stream. Can you remove it from the pipeline to see if it affects det (HDDL) + cls (HDDL) performance in a positive way?

**Comment by nsk-lab** [comment] 2020-11-24 01:02
@Andruxin52rus 

#### 1. HW info :

CPU ： Intel® Atom™ x5-E3930 1.3GHz
MEM ： 8GB
VPU ： Movidius™ Myriad™ X VPU x2

#### 2. I removed gvawatermark and changed fpsdisplaysink to gvafpscounter, but there was no improvement.

■ using face movie (head-pose-face-detection-female-and-male.mp4)
[FACE] detection(HDDL)+1-classification( CPU) ⇒ 42.79 FPS
[FACE] detection(HDDL)+1-classification(HDDL) ⇒ 24.19 FPS

■ using NO-face movie (I used "videotestsrc" gstreamer element as input)
[NO-FACE] detection(HDDL)+1-classification( CPU) ⇒ 48 FPS
[NO-FACE] detection(HDDL)+1-classification(HDDL) ⇒ 24 FPS


command line
```
gst-launch-1.0 filesrc location=head-pose-face-detection-female-and-male.mp4 ! decodebin ! videoconvert ! video/x-raw,format=I420 ! \
gvadetect model=/home/ubuntu/intel/dl_streamer/models/intel/face-detection-adas-0001/FP16/face-detection-adas-0001.xml device=$DEVICE1 ! queue ! \
gvaclassify model=/home/ubuntu/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP16/age-gender-recognition-retail-0013.xml model-proc=./model_proc/age-gender-recognition-retail-0013.json device=$DEVICE2 ! queue ! \
gvafpscounter ! fakesink
```

**Comment by nsk-lab** [comment] 2020-11-24 02:05
I set device_snapshot_mode : "full" in /opt/intel/openvino_2021/inference_engine/external/hddl/config/hddl_service.config
and checked /var/log/syslog

It seems that one VPU is occupied by secondary model.
Is it a hardware limitation or software limitation?

■ using NO-face movie (I used "videotestsrc" gstreamer element as input)

□ detection(HDDL)+1-classification( CPU) 

```
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: [18:30:16.5814][2413]I[DeviceManager.cpp:916] DeviceSnapshot(subclass=0):
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | deviceId    | 224(0xe0)         | 225(0xe1)         |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | device      | 4.1               | 4.2               |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | util%       | 100.00 %          | 100.00 %          |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | thermal     | 46.90(0)          | 46.68(0)          |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | scheduler   | squeeze           | squeeze           |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | comment     |                   |                   |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | resetTimes  | 0                 | 0                 |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | cacheNum    | 1                 | 1                 |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | cacheGraph0 | mobilen...672x384 | mobilen...672x384 |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | cacheGraph1 |                   |                   |
Nov 24 18:30:16 ubuntu-SJ45 hddldaemon: | cacheGraph2 |                   |                   |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | cacheGraph3 |                   |                   |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: +-------------+-------------------+-------------------+
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | status      | RUNNING           | RUNNING           |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | fps         | 24.13             | 24.11             |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | curGraph    | mobilen...672x384 | mobilen...672x384 |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | rPriority   | 0                 | 0                 |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | loadTime    | 20201124 18:29:39 | 20201124 18:29:39 |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | runTime     | 00:00:37          | 00:00:37          |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | inference   | 888               | 888               |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | prevGraph   |                   |                   |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | loadTime    |                   |                   |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | unloadTime  |                   |                   |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | runTime     |                   |                   |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: | inference   |                   |                   |
Nov 24 18:30:18 ubuntu-SJ45 hddldaemon: +-------------+-------------------+-------------------+
```

□ detection(HDDL)+1-classification(HDDL) 
```
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: [18:32:06.5921][2413]I[DeviceManager.cpp:916] DeviceSnapshot(subclass=0):
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | deviceId    | 224(0xe0)         | 225(0xe1)         |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | device      | 4.1               | 4.2               |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | util%       | 100.00 %          | 0.0 %             |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | thermal     | 46.68(0)          | 43.04(0)          |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | scheduler   | squeeze           | squeeze           |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | comment     |                   |                   |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | resetTimes  | 0                 | 0                 |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | cacheNum    | 1                 | 2                 |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | cacheGraph0 | mobilen...672x384 | mobilen...672x384 |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | cacheGraph1 |                   | age_gender        |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | cacheGraph2 |                   |                   |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | cacheGraph3 |                   |                   |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: +-------------+-------------------+-------------------+
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | status      | RUNNING           | WAIT_TASK         |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | fps         | 24.03             |                   |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | curGraph    | mobilen...672x384 | age_gender        |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | rPriority   | 0                 | 0                 |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | loadTime    | 20201124 18:30:57 | 20201124 18:30:57 |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | runTime     | 00:01:09          | 00:01:08          |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | inference   | 1658              | 0                 |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | prevGraph   |                   |                   |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | loadTime    |                   |                   |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | unloadTime  |                   |                   |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | runTime     |                   |                   |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: | inference   |                   |                   |
Nov 24 18:32:11 ubuntu-SJ45 hddldaemon: +-------------+-------------------+-------------------+
```

**Comment by pk1d3v** [comment] 2020-11-25 14:10
Hello @nsk-lab!  Thank you for sharing your findings.

We managed to reproduce this on our side and we are currently investigating it internally.

**Comment by pk1d3v** [comment] 2021-01-11 10:42
Sorry for the long delay in reply.

The performance can be improved by changing the scheduler mode to SGAD in HDDL service.  To do so, you need to modify `hddl_service.config` file, which is usually located at `/opt/intel/openvino_2021/inference_engine/external/hddl/config/hddl_service.config`.
Here are the changes:
```diff
  "scheduler_config":
  [
    {
      //...  

      // SGAD Scheduler
-      "sgad_device_number":          0,
+      "sgad_device_number":          2,  // number of devices assigned to SGADScheduler
+      "use_sgad_by_default":      true,

      //...
    }
  ],
```

With this configuration of the HDDL service, the case without actual detection _("NO-face movie")_ in HDDL+HDDL configuration shows same performance as HDDL+CPU in our tests. 
And the case with actual detection _("face movie")_ in HDDL+HDDL configuration shows slightly less performance comparing to HDDL+CPU. This is because in HDDL+CPU scenario, all VPUs resources are spent on detection, while in HDDL+HDDL scenario, part of VPU resources are spent on classification in addition to detection. Hence the difference in performance.

We are going to close this issue. If you are still experiencing problems, please let us know.

**Comment by mliu2020** [comment] 2021-01-12 00:32
This solution was confirmed with customer through emails and solution was accepted.

So this issue is closed.

Mark

**Closed by mliu2020** 2021-01-12 00:32 UTC
