### ISSUE TITLE
vehicle_pedestrian_tracking sample not support gvatrack GPU?

### ISSUE THREAD

**Issue by wdkwyf** [openvinotoolkit/dlstreamer_gst#224] opened 2021-08-03 09:50 UTC
Hi, when I run the vehicle_pedestrian_tracking demo, with gvatrack device=GPU, error occurred:
```
628069100769892	W	[                                                            :0    ]	CreateRGBFeatureComputer 0 0
0:00:10.322148861 220065 0x563ad3bc7b00 ERROR               gvatrack tracker.cpp:208:track: Exception within tracker occured: Unsupported runtime format for surface.
Error /GstPipeline:pipeline0/GstGvaTrack:gvatrack0：transform_ip failed
Additional debug information
/root/gst-video-analytics/gst/elements/gvatrack/gstgvatrack.c(295): gst_gva_track_transform_ip (): /GstPipeline:pipeline0/GstGvaTrack:gvatrack0:

Track: error while tracking objects
```

My command: 
`/vehicle_pedestrian_tracking.sh ~/hospital_20_40.mp4 1 GPU display zero-term`

And I follow [this guide](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/DPCPP-Install-Guide) to install dpcpp compiler and replace the vasot_gpu.so file, but still occurred error. Could you please help?
OpenVINO version                          2021.4.582
OS                                                   ubuntu 20
Driver Version                                  21.19.19792
Device Name                                   Intel(R) Iris(TM) Pro Graphics 580 [0x193b]

**Comment by mliu2020** [comment] 2021-08-03 16:55
Hi @wdkwyf,

Thanks for the report, let me try it on my side and see if it can be reproduced.

Mark

**Comment by wdkwyf** [comment] 2021-08-04 05:55
> Hi @wdkwyf,
> 
> Thanks for the report, let me try it on my side and see if it can be reproduced.
> 
> Mark

Thank you Mark! If any update, please kindly inform me.

**Comment by mliu2020** [comment] 2021-08-10 03:22
Hi @wdkwyf,

Sorry for the late response, I tried your command line but I didn't get failure.

I used `./vehicle_pedestrian_tracking.sh <video file> 1 GPU display zero-term`. I had some error when loading the DPCPP library from vasot_gpu.so since I didn't install it but the pipeline was running and rendering normally, is this the same behavior you observed?

I run it with IceLake machine with Intel® Iris® Plus Graphics and I have found 1 OpenCL device with "clinfo" command. What was your platform?

Mark

**Comment by wdkwyf** [comment] 2021-08-10 03:28
> Hi @wdkwyf,
> 
> Sorry for the late response, I tried your command line but I didn't get failure.
> 
> I used `./vehicle_pedestrian_tracking.sh <video file> 1 GPU display zero-term`. I had some error when loading the DPCPP library from vasot_gpu.so since I didn't install it but the pipeline was running and rendering normally, is this the same behavior you observed?
> 
> I run it with IceLake machine with Intel® Iris® Plus Graphics and I have found 1 OpenCL device with "clinfo" command. What was your platform?
> 
> Mark

Hi, did you change the gvatrack device=GPU?
I'm afriad it's the dpcpp install or ubuntu kernel issue, because I try the devcloud for oneAPI, it works. 
But the gvatrack-GPU performance is not good, could you please provide such gavtrack-GPU speed-up information? Thanks.

**Comment by mliu2020** [comment] 2021-08-11 01:47
Thanks,

You are correct, I changed it in the script and I can reproduce it now. I will discuss with dev team about it.

About the gvatrack-GPU performance, are you looking for FPS number in GPU vs. CPU? If convenient, could you post a new issue with the command line and number you observed?

Mark Liu

**Comment by wdkwyf** [comment] 2021-08-11 02:10
Thanks, Mark. I post another issue according to the perf issue:https://github.com/openvinotoolkit/dlstreamer_gst/issues/225




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "openvinotoolkit/dlstreamer_gst"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Aug 11, 2021 09:47 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [openvinotoolkit/dlstreamer_gst] vehicle_pedestrian_tracking sample not support gvatrack GPU? (#224)





 
Thanks,
 
You are correct, I changed it in the script and I can reproduce it now. I will discuss with dev team about it.
 
About the gvatrack-GPU performance, are you looking for FPS number in GPU vs. CPU? If convenient, could you post a new issue with the command line and number you observed?
 
Mark Liu
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mliu2020** [comment] 2021-08-17 18:53
Hi @wdkwyf,

This issue was sent to dev team for investigation, I will keep you updated.

Mark

**Comment by ymaskina** [comment] 2021-09-30 10:45
Hi @wdkwyf,

I can't reproduce it on my system and in our docker images, looks like it is environment problem indeed.
Can we close this issue or you need help with dependencies installation?

Best regards,
Yuliya

**Closed** 2021-11-25 14:57 UTC
Labels: bug
