### ISSUE TITLE
CMake fail - Windows Install Guide

### ISSUE THREAD

**Issue by psakamoori** [openvinotoolkit/dlstreamer_gst#210] opened 2021-04-20 18:45 UTC
Facing Cmake build errors after following instruction as mentioned here https://github.com/openvinotoolkit/dlstreamer_gst/wiki/%5BPreview%5D-Windows-Install-Guide

Logs:

cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.28.29914.0
-- The CXX compiler identification is MSVC 19.28.29914.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
CMake Warning at CMakeLists.txt:27 (message):
  VERSION_PATCH is undefined.  Set default value 0.

CMake Warning at CMakeLists.txt:32 (message):
  GIT_INFO is undefined.  Set default value 0.

-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  **Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)**
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.20/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  CMakeLists.txt:83 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/thor/intel/dlstreamer_gst/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/thor/intel/dlstreamer_gst/build/CMakeFiles/CMakeError.log".

==================
Setup details:

Window Build Version:

Edition: Windows 10 Enterprise 2016 LTSB
Version 1607
OS Build: 14393.3808

**Comment by psakamoori** [comment] 2021-04-20 18:49
After setting/adding this to system variables (which is not mentioned in the release notes) "PKG_CONFIG_EXECUTABLE"  like (PKG_CONFIG_EXECUTABLE = %USERPROFILE%\pkg-config\bin) seeing below error logs

C:\Users\thor\intel\dlstreamer_gst\build>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.28.29914.0
-- The CXX compiler identification is MSVC 19.28.29914.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
CMake Warning at CMakeLists.txt:27 (message):
  VERSION_PATCH is undefined.  Set default value 0.


CMake Warning at CMakeLists.txt:32 (message):
  GIT_INFO is undefined.  Set default value 0.


-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

      Reason given by package: The command
        "C:/Users/thor/pkg-config/bin/pkg-config.exe" --version
      failed with output:



      stderr:

      result:

  Exit code 0xc0000135



Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.20/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  CMakeLists.txt:83 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/thor/intel/dlstreamer_gst/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/thor/intel/dlstreamer_gst/build/CMakeFiles/CMakeError.log".


=========================
When tried to run pkg-config.exe getting below error

![image](https://user-images.githubusercontent.com/2974647/115448325-95f04180-a1e7-11eb-98cf-529b6308dd4c.png)

**Comment by mliu2020** [comment] 2021-04-20 22:48
Hi @psakamoori,

I want to investigate and read the release page, there are 2 options, installation on host and installation on Docker. Which path did you use?

Mark

**Comment by psakamoori** [comment] 2021-04-21 00:09
@mliu2020 Followed Option1 - Will give a try with Option2 as well

**Comment by psakamoori** [comment] 2021-04-21 00:57
@mliu2020 Is this right branch for option2:

C:\Users\thor\intel>git clone -b **_preview/windows-support_** https://github.com/openvinotoolkit/dlstreamer_gst.git %USERPROFILE%\intel\dlstreamer_gst
Cloning into 'C:\Users\thor\intel\dlstreamer_gst'...
fatal: Remote branch preview/windows-support not found in upstream origin

**Comment by adranit** [comment] 2021-04-21 08:55
Hi @psakamoori,
Branch name is wrong. Please use the following command:

git clone -b preview/support-for-windows https://github.com/openvinotoolkit/dlstreamer_gst.git %USERPROFILE%\intel\dlstreamer_gst

**Comment by mliu2020** [comment] 2021-04-22 21:08
@psakamoori,

Sorry for the late response, I try the host path on my side and I can build it successfully although I got some problem when I run the pipeline.

Here are something I did different from the installation and you might try it:
- I installed CMake 3.20.1 64bit since that is the default from the page, I have to change the PATH since I had a Python 3.7 32bit previously
- pkg-config: I found the original link point to 32bit but python and gstreamer is 64bit, so I did this package https://download.gnome.org/binaries/win64/dependencies/pkg-config_0.23-2_win64.zip
- glib: the same reason above, I used 64bit https://ftp.acc.umu.se/pub/GNOME/binaries/win64/glib/2.26/glib_2.26.1-1_win64.zip
- I have to turn off proxy since some of the script will fail.
- I didn't run install_prerequisites.bat since it was blocked by TF 2.2 installation

Here is the cmake output:
C:\Users\developer\intel\dlstreamer_gst\build>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
CMake Warning at CMakeLists.txt:27 (message):
  VERSION_PATCH is undefined.  Set default value 0.


CMake Warning at CMakeLists.txt:32 (message):
  GIT_INFO is undefined.  Set default value 0.


-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found PkgConfig: C:/pkg-config-lite-0.28-1/bin/pkg-config.exe (found version "0.28")
-- Checking for module 'gstreamer-1.0>=1.16'
--   Found gstreamer-1.0, version 1.16.2
ENABLE_VAS_TRACKER is set to OFF. gvatrack element won't be available
ENABLE_PAHO_INSTALLATION=OFF
ENABLE_RDKAFKA_INSTALLATION=OFF
-- Checking for module 'gstreamer-video-1.0>=1.16'
--   Found gstreamer-video-1.0, version 1.16.2
-- Checking for module 'gstreamer-allocators-1.0'
--   Found gstreamer-allocators-1.0, version 1.16.2
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.56.1
-- Found OpenCV: C:/Program Files (x86)/Intel/openvino_2021/opencv (found version "4.5.2") found components: core imgproc
-- Checking for module 'gstreamer-audio-1.0>=1.16'
--   Found gstreamer-audio-1.0, version 1.16.2
MQTT support will not be available. Ensure required libraries (Paho MQTT) are installed, and rebuild plugin with -DMQTT=1 before attempting to use MQTT
Kafka support will not be available. Ensure required libraries (librdkafka) are installed, and rebuild plugin with -DKAFKA=1 before attempting to use Kafka
-- Checking for module 'pygobject-3.0'
--   No package 'pygobject-3.0' found
-- Found PythonLibs: C:/Users/developer/AppData/Local/Programs/Python/Python39/libs/python39.lib (found suitable version "3.9.4", minimum required is "3.4")
-- Found InferenceEngine: C:/Program Files (x86)/Intel/openvino_2021/deployment_tools/inference_engine/lib/intel64/Release/inference_engine.lib (Required is at least version "2.1.0")
-- Found OpenCV: C:/Program Files (x86)/Intel/openvino_2021/opencv (found version "4.5.2") found components: core imgproc imgcodecs
-- [download 100% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 38% complete]
-- [download 40% complete]
-- [download 42% complete]
-- [download 44% complete]
-- [download 46% complete]
-- [download 48% complete]
-- [download 50% complete]
-- [download 52% complete]
-- [download 54% complete]
-- [download 56% complete]
-- [download 58% complete]
-- [download 60% complete]
-- [download 62% complete]
-- [download 64% complete]
-- [download 66% complete]
-- [download 68% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 73% complete]
-- [download 75% complete]
-- [download 77% complete]
-- [download 79% complete]
-- [download 81% complete]
-- [download 83% complete]
-- [download 85% complete]
-- [download 87% complete]
-- [download 89% complete]
-- [download 91% complete]
-- [download 93% complete]
-- [download 95% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 100% complete]
-- [download 100% complete]
-- Found OpenCV: C:/Program Files (x86)/Intel/openvino_2021/opencv (found version "4.5.2") found components: core imgproc
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/developer/intel/dlstreamer_gst/build

Let me know if you have any questions.

Mark

**Comment by psakamoori** [comment] 2021-04-23 18:22
@mliu2020 Will give it a try with your steps above

**Comment by psakamoori** [comment] 2021-04-23 19:56
C:\Users\thor\intel\dlstreamer_gst\build>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.14393.
-- The C compiler identification is MSVC 19.28.29914.0
-- The CXX compiler identification is MSVC 19.28.29914.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
CMake Warning at CMakeLists.txt:27 (message):
  VERSION_PATCH is undefined.  Set default value 0.


CMake Warning at CMakeLists.txt:32 (message):
  GIT_INFO is undefined.  Set default value 0.


-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

      Reason given by package: The command
        "C:/Users/thor/pkg-config/bin/pkg-config.exe" --version
      failed with output:



      stderr:

      result:

  Exit code 0xc0000135



Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  CMakeLists.txt:83 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/thor/intel/dlstreamer_gst/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/thor/intel/dlstreamer_gst/build/CMakeFiles/CMakeError.log".

**Comment by psakamoori** [comment] 2021-04-23 20:04
@mliu2020  Howz your PKG_CONFIG_EXECUTABLE path looking?

C:\Users\thor\intel\dlstreamer_gst\build>cmake ..
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.14393.
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
CMake Warning at CMakeLists.txt:27 (message):
  VERSION_PATCH is undefined.  Set default value 0.


CMake Warning at CMakeLists.txt:32 (message):
  GIT_INFO is undefined.  Set default value 0.


CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

      Reason given by package: The command
        "C:/Users/thor/pkg-config/bin/pkg-config.exe" --version
      failed with output:



      stderr:

      result:

  Exit code 0xc0000135



Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  CMakeLists.txt:83 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/thor/intel/dlstreamer_gst/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/thor/intel/dlstreamer_gst/build/CMakeFiles/CMakeError.log".

**Comment by mliu2020** [comment] 2021-04-23 22:35
No, I don't have it.

My environment has MSYS2, so you might check if you need to [install MSYS2-based tools](https://www.msys2.org/). 

Mark

**Comment by psakamoori** [comment] 2021-04-26 17:57
Mark, Setup is not behind any proxy. Also, tried with MSYS2 installation - Still the same error.
Can you confirm if  build supports before version of windows and HW
Edition: Windows 10 Enterprise 2016 LTSB
Version: 1607
OS Build: 14393.3808
Processor: Intel(R) Core(TM) i3-6100U

**Comment by mliu2020** [comment] 2021-05-01 02:14
@psakamoori ,

Sorry for the late response, to answer your questions:

1. PATH is the Windows environment variable, I have to modify since the default Python is 32bit, I was trying to make sure the Python version is 64bit. In general, I tried to be careful so all the tools are set to 64bit.
2. Sorry I don't have this hardware in hand. I don't think pkg-config must match the Windows build version. But I would make sure it is 64bit.
3. I checked [this post](https://stackoverflow.com/questions/33380020/errorcould-not-find-pkgconfig-missing-pkg-config-executable), it says you got "Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)" error because cmake can't find pkg-config utilities, please make sure the pkg-config utility installation directory is in PATH environment variable, in my case this is "C:\pkg-config-lite-0.28-1\bin"

Mark

**Comment by psakamoori** [comment] 2021-05-03 00:22
@mliu2020  I will check the above..Mean while I moved to 19041.928 Windows10 Build version and facing below error..

C:\Users\psakamoori\intel\dlstreamer_gst\docker\Windows> ./build_docker_image.bat https://registrationcenter-download.intel.com/akdlm/irc_nas/17661/w_openvino_toolkit_p_2021.3.394_online.exe win10dlstreamer
[+] Building 0.6s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/windows/servercore/iis:latest                             0.5s
------
 > [internal] load metadata for mcr.microsoft.com/windows/servercore/iis:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:69d0cfcb09c24714aff3c25fffbdcd04500eb5dfe9629c17ab2be97da2d1d5f6: not found

**Comment by psakamoori** [comment] 2021-05-03 21:09
Tried with different tags - non-working....

C:\Users\psakhamo\intel\dlstreamer_gst\docker\Windows>build_docker_image.bat https://registrationcenter-download.intel.com/akdlm/irc_nas/17661/w_openvino_toolkit_p_2021.3.394.exe win10_dlstreamer mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
Sending build context to Docker daemon  10.75kB
Step 1/45 : ARG BASE_IMAGE=mcr.microsoft.com/windows/servercore/iis
Step 2/45 : FROM ${BASE_IMAGE}
windowsservercore-ltsc2019: Pulling from windows/servercore/iis
4612f6d0b889: Pulling fs layer                                                                                          399f118dfaa9: Pulling fs layer                                                                                          2a9b66f90273: Pulling fs layer                                                                                          a4473713814e: Waiting                                                                                                   370331a9254d: Waiting                                                                                                   image operating system "windows" cannot be used on this platform

C:\Users\psakhamo\intel\dlstreamer_gst\docker\Windows>build_docker_image.bat https://registrationcenter-download.intel.com/akdlm/irc_nas/17661/w_openvino_toolkit_p_2021.3.394.exe win10_dlstreamer mcr.microsoft.com/windows/servercore/iis:windowsservercore-1909
Sending build context to Docker daemon  10.75kB
Step 1/45 : ARG BASE_IMAGE=mcr.microsoft.com/windows/servercore/iis
Step 2/45 : FROM ${BASE_IMAGE}
windowsservercore-1909: Pulling from windows/servercore/iis
9038b92872bc: Pulling fs layer                                                                                          c7ed3ffefdad: Pulling fs layer                                                                                          1f033ad64c0a: Pulling fs layer                                                                                          fd5ee026b59b: Waiting                                                                                                   efba0e1c10bb: Waiting                                                                                                   image operating system "windows" cannot be used on this platform

C:\Users\psakhamo\intel\dlstreamer_gst\docker\Windows>build_docker_image.bat https://registrationcenter-download.intel.com/akdlm/irc_nas/17661/w_openvino_toolkit_p_2021.3.394.exe win10_dlstreamer mcr.microsoft.com/windows/servercore/iis:windowsservercore-20H2
Sending build context to Docker daemon  10.75kB
Step 1/45 : ARG BASE_IMAGE=mcr.microsoft.com/windows/servercore/iis
Step 2/45 : FROM ${BASE_IMAGE}
windowsservercore-20H2: Pulling from windows/servercore/iis
18ae6bebe21d: Pulling fs layer                                                                                          ad702b8ea1d8: Pulling fs layer                                                                                          5481ef19cda6: Pulling fs layer                                                                                          ccfb87c0424b: Waiting                                                                                                   cb15c554c1f5: Waiting                                                                                                   image operating system "windows" cannot be used on this platform

**Comment by mliu2020** [comment] 2021-05-03 21:55
Hi @psakamoori,

I didn't check docker image build yet so I don't know the details. But from the error message, it seems you have an access issue to mcr.microsoft.com/windows/servercore/iis.

My understanding is, the Windows IIS setup the environment for the rest of docker build commands, were you behind a firewall?

Mark

**Comment by psakamoori** [comment] 2021-05-03 23:35
Hi @mliu2020  Even when building with source code..its failing even with right cmake path..(to \bin dir)

C:\Users\psakhamo\intel\dlstreamer_gst\build>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.28.29914.0
-- The CXX compiler identification is MSVC 19.28.29914.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is undefined. Set default build type Release.
CMake Warning at CMakeLists.txt:27 (message):
  VERSION_PATCH is undefined.  Set default value 0.


CMake Warning at CMakeLists.txt:32 (message):
  GIT_INFO is undefined.  Set default value 0.


-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

      Reason given by package: The command
        "C:/Users/psakhamo/pkg-config/bin/pkg-config.exe" --version
      failed with output:



      stderr:

      result:

  Exit code 0xc0000135



Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  CMakeLists.txt:83 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/psakhamo/intel/dlstreamer_gst/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/psakhamo/intel/dlstreamer_gst/build/CMakeFiles/CMakeError.log".

**Comment by psakamoori** [comment] 2021-05-03 23:36
> Hi @psakamoori,
> 
> I didn't check docker image build yet so I don't know the details. But from the error message, it seems you have an access issue to mcr.microsoft.com/windows/servercore/iis.
> 
> My understanding is, [the Windows IIS](https://hub.docker.com/_/microsoft-windows-servercore-iis) setup the environment for the rest of docker build commands, were you behind a firewall?
> 
> Mark

**Comment by psakamoori** [comment] 2021-05-03 23:38
> Hi @psakamoori,
> 
> I didn't check docker image build yet so I don't know the details. But from the error message, it seems you have an access issue to mcr.microsoft.com/windows/servercore/iis.
> 
> My understanding is, [the Windows IIS](https://hub.docker.com/_/microsoft-windows-servercore-iis) setup the environment for the rest of docker build commands, were you behind a firewall?
> 
> Mark

Yes, not behind firewall...

**Comment by mliu2020** [comment] 2021-07-06 21:11
Hi @psakamoori,

I think we already solved this internally and let me close this request for clean up. Feel free to reopen it.

Root cause, seems like pkg-config we refer in our instruction is not working at all with this Windows version.:
Edition: Windows 10 Enterprise 2016 LTSB
Version 1607
OS Build: 14393.3808

Following work-around can install pkg-config. Assuming you have installed msys, you can use these commands to install it:
msys32\autorebase.bat
pacman -Syu  # to update the system packages
pacman -S mingw-w64-x86_64-pkg-config
 
reference: https://stackoverflow.com/a/26476504
 
After that you added it to PATH:
set PATH=%PATH%;C:\msys64\mingw64\bin
 
You should also make sure gstreamer-1.0 installed.

Mark

**Closed by mliu2020** 2021-07-06 21:11 UTC
