### ISSUE TITLE
Real-time streaming from camera or network

### ISSUE THREAD

**Issue by matanster** [openvinotoolkit/dlstreamer_gst#193] opened 2021-03-07 15:15 UTC
Hi,

I have read in the readme that real-time streaming from camera or network is supported. I'd like to learn please whether there is any back-pressure built into this pipeline framework that this repo implements. Or if not, whether any other design pattern is implemented for operating the pipeline at real-time (i.e. in a way that is not slower than the input rate, nor discarding, on average, a lot of pipeline work while rate limiting itself). Any comments will be very useful. 

Otherwise, happy to learn your experiences in tuning streaming input rate in user code.

I read [somewhere](https://coaxion.net/blog/2018/04/improving-gstreamer-performance-on-a-high-number-of-network-streams-by-sharing-threads-between-elements-with-rusts-tokio-crate/) and seem to see in [the RTSP part of Gstreamer](https://github.com/GStreamer/gst-rtsp-server/search?q=backpressure&type=code) that Gstreamer applies back-pressure, but not quite sure how this factors in when using DL-Streamer. 

Thanks!

**Comment by mliu2020** [comment] 2021-03-09 06:27
@matanster,

Sorry for the late response.

If my understanding is correct, "back-pressure" means the workload is too heavy and frames being dropped.

As my understanding, the overloading can be caused by many issues, for visual analytics pipeline, we should have following potential bottlenecks:
- video resolution and frame rate, in the real-time case, can I assume 25~30FPS in your case?
- Inference Engine: this depends on the model you used, how many stages of inference operation.
- How do you want to output? Do you need rendering or just metadata.
- The hardware capability: if you use a low end processor but video encode/decode can be offload to hardware, this can help you to increase the performance while keep the cost low.
- About lost frame, what is your target? Lost video frame or lost inference frame. You might not do inference for each frame but keeps all the video frame, this is why we have an argument called "inference-interval" and gvatrack element which can skip the frame while keep the inference result consistent.

So it really depends on the application and hardware capabilities, but in general, if you can offload video to GPU, the bottleneck would comes more from inference, both openVINO and GStreamer offers the parallel processing for improvement.

Let me know if this answers your question.

Mark Liu

**Comment by matanster** [comment] 2021-03-09 20:42
Thanks a lot Mark for pointing out how to tune this with the inference-interval. I think the definition of back-pressure is just a tad more recursive ... every stage of the pipeline will ignore input (push back the pressure) when it can't handle the rate of its input. This also implies that earlier processing stages may limit the rates to their inputs in turn, thus reducing energy or contention across stages on the compute resources.

Sometimes it is fully automated by the pipeline framework, so that it works optimally on any hardware stack without the need for manual tuning of any parameters, but I'd imagine that the quality of this property varies across projects that claim it as there may be many probabilistic approaches and fine-tunes for such a throttling process.

If you may excuse my C project code navigation for a minute, is `inference-interval` something that can be currently dynamically set, or does it have to be set only at initialization?

Since Gstreamer is probably back-pressuring, this single parameter might provide much of the same benefit, albeit, if there is a cascade of inference models on the DL Streamer pipeline there may occur inefficient setups where one inference stage is needlessly too fast for its downstream inference stage and consuming needless energy or possibly competing with the downstream inference stages for CPU/GPU time. 

By the way, a project with some parallel lines, Google MediaPipe, handles these aspects [their own peculiar ways](https://google.github.io/mediapipe/framework_concepts/synchronization.html#flow-control). Perhaps hooking all inference stages into Gstreamer gets its magic treatment on this aspect for free, but I don't really know.

**Comment by mliu2020** [comment] 2021-03-10 00:16
Hi @matanster,
`inference-interval` sets the pipeline at the initialization time, so you can't change it dynamically. Normally, DL Streamer inference elements runs for 2 stages, this can be seen in most of the customer pipeline. If the inference-interval is set in the gvadetect element at the beginning of the pipeline, then for the skipped frame, there is no ROI attached, the following inference element will also skip this frame while gvatrack element makes sure no bound box missing.

Does this answers your question?

If you still have concerns, I would suggest you to try our [sample code](https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples) with your content and see if there is any frame skiped. I can help you if you have any questions.

Mark

**Comment by mliu2020** [comment] 2021-04-01 23:02
Hi @matanster,

I read the links you referred and I found [this message](https://github.com/GStreamer/gst-rtsp-server/blob/master/NEWS#L1348) about GStreamer new release.

I believe this is the back-pressure, you were talking about. This should be the RTSP server to handle a slow response device when it sends the message to many devices. From this context, the back-pressure means to remove the slower device from the server list of clients, the server performance will be impacted if it doesn't remove.

If this is right, I can't see anything to do with DL Streamer. Do you agree?

Mark Liu

**Comment by matanster** [comment] 2021-04-02 21:16
It's certainly _related_, but a different scenario. I wouldn't want to keep anyone busy with this question type issue going forward though.

**Comment by mliu2020** [comment] 2021-04-06 04:52
Hi @matanster,

Sorry I might not quit understand you: Are you saying if DL Streamer receives multiple camera streams, it will have the same issue as the server case to build up the back-pressure if there is a slower device?

I don't want to miss any good suggestions before I close this.

Mark Liu

**Comment by mliu2020** [comment] 2021-05-06 23:09
@matanster ,

Thanks for the good input, let me close it now.

Mark

**Closed by mliu2020** 2021-05-06 23:09 UTC
