### ISSUE TITLE
gvatrack error

### ISSUE THREAD

**Issue by zizo1111** [openvinotoolkit/dlstreamer_gst#168] opened 2020-12-15 15:58 UTC
Hi, 
I have extended the example provided in c++,  by adding the element gvatrack, and changed  a couple of things in order to detect and track cars, although i am facing the issue that the tracker throws the following error: 

`OpenCV Error: Bad argument (Unknown interpolation method) in resize, file /build/opencv-SWG7hS/opencv-3.2.0+dfsg/modules/imgproc/src/imgwarp.cpp, line 3367
0:00:03.747921807  2755 0x7fbe20003a10 ERROR                default tracker.cpp:122:track: Exception within tracker occured: /build/opencv-SWG7hS/opencv-3.2.0+dfsg/modules/imgproc/src/imgwarp.cpp:3367: error: (-5) Unknown interpolation method in function resize
`
The error gets thrown from the gvatrack element itself.

I am Using Ubuntu 18
openvino_2020.4.287

Thanks

**Comment by adranit** [comment] 2020-12-16 12:31
Hi @zizo1111 ,
It looks like wrong OpenCV version (opencv-3.2.0+dfsg) was linked with the app. Gvatrack element from openvino_2020.4.287 should be used with the OpenCV 4.4.0 that is a part of OpenVino installation. Could you double check that the app uses the appropriate OpenCV version?

**Comment by mliu2020** [comment] 2020-12-21 19:20
Hi @zizo1111,

The library file of @adranit comment is at /opt/intel/openvino_2020.4.287/opencv/lib or <openVINO install dir>/opencv/lib. You should make sure your environment point to it.

Let me know if this advice doesn't solve your problem.

Mark

**Comment by zizo1111** [comment] 2020-12-22 09:26
Hi @adranit @mliu2020 ,
Thanks for the reply, the reason here for my problem is that i am using ROS and Openvino together, ROS has only opencv 3.2 while openvino has 4.4, so basically i face problems with either one when i am using the other version of opencv.

**Comment by mliu2020** [comment] 2020-12-23 04:37
Thanks @zizo1111,

Could you find a way to use them at the same time, or isolate them in their own environment like Docker?

Mark

**Comment by mliu2020** [comment] 2020-12-30 17:27
Hi @zizo1111,

I believe we found the root cause and it is related to your environment, do you find a way to solve it yet?

Mark

**Comment by mliu2020** [comment] 2021-01-11 22:09
Hi @zizo1111,

Since you agreed with our analysis and no further request, I believe the problem was solved.

Let me close this issue for now and feel free to re-open it if you still need help.

Mark

**Closed by mliu2020** 2021-01-11 22:09 UTC
