### ISSUE TITLE
Facing OOM issue while running multiple streams via RTSP Media Factory

### ISSUE THREAD

**Issue by Pulkit0810** [openvinotoolkit/dlstreamer_gst#172] opened 2020-12-30 16:47 UTC
Hello Team,

While connecting the client with the RTSP server, one RTSPMediaFactory instance is created and with the help of that instance, we set some properties like "set_transport_mode", "set_launch", "set_shared" and start the streaming for client to server.
But after 10-11 hour, server get crash and showing out of memory.
I have used 10GB memory, 

> In the begning:
> Memory: 1GB
> After crash
> Memory - 10GB

**Server**:
> server = GstRtspServer.RTSPServer.new()
> factory = GstRtspServer.RTSPMediaFactory.new()
> server.connect("client-connected", client_connected)
> 
> def client_connected(server, client):
>     factory.set_transport_mode(GstRtspServer.RTSPTransportMode.RECORD)
>     factory.set_launch(pipeline)
>     factory.set_shared(True)
>     mounts.add_factory("/traffic", factory)
> 
> pipeline="decodebin name=depay0 ! videoconvert ! gvafpscounter ! fakesink"

and this function (client_connected) always call when adding a new stream.
@dsmertin , @mliu2020 , Can you please check where I am wrong!

Thanks 
Pulkit

**Comment by Pulkit0810** [comment] 2020-12-31 16:36
Is there any model size issue which is taking more memory on every new client?

**Comment by mliu2020** [comment] 2020-12-31 23:47
Hi @Pulkit0810,

Sorry for the late response, I want to reproduce your error with a local client and I am still working on it. I wonder if you tried to remove gvacounter and see.

Mark

**Comment by Pulkit0810** [comment] 2021-01-09 17:58
> Hi @Pulkit0810,
> 
> Sorry for the late response, I want to reproduce your error with a local client and I am still working on it. I wonder if you tried to remove gvacounter and see.
> 
> Mark

Hello @mliu2020 , 

We are using road segmentation model,
When we run client in loop,  where client connect one after the other, then it creates number of threads and these threads are probably holding memory which keeps on accumulating.
Within 30 minutes,  the application consumes around 8GB.
Below is my pipeline
> gst-launch-1.0 decodebin name=depay0 ! videorate ! videoconvert ! video/x-raw,format=BGR ! gvainference model-instance-id={}_fdet model={} no-block=true inference-interval=4 device={} ! queue leaky=downstream ! gvafpscounter ! fakesink

It consumes 8 gb memory in 1hour.
Also i have checked with top command, 
I am seeing the multiple threads named as queue:src and rtpjittrbuffer using memory

**My question is:**
What are the changes i might need in the current pipeline or what should be done to that the memory accumulation stops and resources gets freed up on evey client’s EOS?


Pulkit

**Comment by mliu2020** [comment] 2021-01-12 06:58
Hi @Pulkit0810,

Sorry for delayed response, I am trying to reproduce this issue by using an RTSP stream which can loop on a video to create an endless video stream.

I used a pipeline similar to yours only changed the input but I seems didn't observe the OOM, I will leave it running for over night but want to double check, how did you check the memory usage?

Mark

**Comment by Pulkit0810** [comment] 2021-01-12 07:06
> Hi @Pulkit0810,
> 
> Sorry for delayed response, I am trying to reproduce this issue by using an RTSP stream which can loop on a video to create an endless video stream.
> 
> I used a pipeline similar to yours only changed the input but I seems didn't observe the OOM, I will leave it running for over night but want to double check, how did you check the memory usage?
> 
> Mark

Hi @mliu2020 

By using the below command:
> cat /sys/fs/cgroup/memory/memory.usage_in_bytes


Pulkit

**Comment by mliu2020** [comment] 2021-01-12 07:44
Thanks, 

I tried it and the memory reading is different from `top` or system monitor, I will leave the program running for several hour and see if there is a big number increase.

Mark

**Comment by mliu2020** [comment] 2021-01-12 20:18
Hi @Pulkit0810,

I used the number by your command and it increased 546MB while `top` shows about 900MB in virtual memory but I don't get OOM error.

The pipeline I used is `gst-launch-1.0 -v rtspsrc location=rtsp://my_url.sdp ! rtph264depay ! decodebin ! video/x-raw ! gvainference model-instance-id=inf0 model=/home/developer/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml no-block=true inference-interval=4 device=CPU ! queue ! gvafpscounter ! fakesink async=false`

I think we need to do further test:

- For pipeline, do you have any suggestion on my pipeline?
- For memory, I suggest to use `top -p PID` or `pmap PID` so we could refer to the same index.

Let me know if you have other suggestions
Mark

**Comment by mliu2020** [comment] 2021-01-13 23:01
Hi @Pulkit0810,

Our dev team told me they can reproduce it and they will fix the bug.

The issue is reproducible under following condition:

- It must be run under fpscounter only or fpscounter + road segmentation model.
- The pipeline is running with start/stop scenario, feeding a continuous stream will not have this problem.

Hope this is the same observation as yours.

Mark

**Comment by Pulkit0810** [comment] 2021-01-14 07:46
> Hi @Pulkit0810,
> 
> Our dev team told me they can reproduce it and they will fix the bug.
> 
> The issue is reproducible under following condition:
> 
> * It must be run under fpscounter only or fpscounter + road segmentation model.
> * The pipeline is running with start/stop scenario, feeding a continuous stream will not have this problem.
> 
> Hope this is the same observation as yours.
> 
> Mark


Thanks @mliu2020 ,
yes, this issue comes with/without gvafpscounter and also when we feed the stream in loop.
In both scenario, issue is reproducible.
Below is our pipeline:
> gst-launch-1.0 decodebin name=depay0 ! videorate ! videoconvert ! video/x-raw,format=BGR ! gvainference model-instance-id=fdet model=road-segmentation-adas-0001.xml no-block=true inference-interval=3 device=CPU ! fakesink

Pulkit

**Comment by adranit** [comment] 2021-01-18 11:19
Hi @Pulkit0810,
We found out that the decodebin element causes a memory leak in these scenarios. I can recommend explicitly using a software decoder in your pipelines as a workaround. ( for example: "filesrc ! qtdemux ! avdec_h264 ! videoconvert ! ....")
Our tests show that there is no memory leak in this case.
Thanks,
Anton

**Comment by Pulkit0810** [comment] 2021-01-20 05:25
> Hi @Pulkit0810,
> We found out that the decodebin element causes a memory leak in these scenarios. I can recommend explicitly using a software decoder in your pipelines as a workaround. ( for example: "filesrc ! qtdemux ! avdec_h264 ! videoconvert ! ....")
> Our tests show that there is no memory leak in this case.
> Thanks,
> Anton

Thanks for the reply @adranit ,
Let me try once and will get back to you.

Pulkit

**Comment by alekseyfa** [comment] 2021-01-21 09:29
Hi @Pulkit0810,
Some additional details about mem leak. The decodebin element internally takes gst-vaapi elements that use [media-driver](https://github.com/intel/media-driver). We found that the driver is cause of leak. If you want to use a decodebin element with HW decode in your gstreamer pipeline, you need to install latest version of this driver [from sources](https://github.com/intel/media-driver/wiki/How-to-build-and-use-media-driver%3F), or just download and install [latest version of mediaSDK](https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-20.5.1). `vainfo` will help you check the version of the driver you are using.

**Comment by mliu2020** [comment] 2021-01-22 01:59
Hi @Pulkit0810,

The page @alekseyfa referred is good enough to install the latest driver, let us know if you have any issues so we can help.

Mark

**Comment by Pulkit0810** [comment] 2021-01-28 17:44
Hi @mliu2020,

First of all, I want to understand which version of Openvino you suggest to get rid of this memory usage issue. At present , I am using Openvino 2020.2, which I would prefer not updating to any other version.

I ran vainfo and the output I got is below:
> error: XDG_RUNTIME_DIR not set in the environment.
> error: can't connect to X server!
> libva info: VA-API version 1.6.0
> libva info: va_getDriverName() returns -1
> libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
> vaInitialize failed with error code -1 (unknown libva error),exit

So, I installed the latest Media SDK from here: (link) and installed latest version of LibVA

The output of vainfo now shows:
> error: XDG_RUNTIME_DIR not set in the environment.
> error: can't connect to X server!
> libva info: VA-API version 1.10.0
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> vaInitialize failed with error code -1 (unknown libva error),exit

Now I ran the stream the same way, that is feeding stream in loop (Start/Stop way). I have added an memory_profiler to my python code. I still see the memory keeps growing. If the cause is decodebin , I can try removing it, directly replacing it with qtdemux ! avdec_h264| will not work as in my case the source is not a file source but a stream coming from remote client using rtspclientsink=<rtsp://myserverurl:port/>

Could you suggest further ways to get to a solution for this memory growth issue?

Pukit

**Comment by Pulkit0810** [comment] 2021-01-29 05:08
Hi @mliu2020 

First of all, I want to understand which version of Openvino you suggest to get rid of this memory usage issue. At present , I am using Openvino 2020.2, which I would prefer not updating to any other version.

I ran vainfo and the output I got is below:
> error: XDG_RUNTIME_DIR not set in the environment.
> error: can't connect to X server!
> libva info: VA-API version 1.6.0
> libva info: va_getDriverName() returns -1
> libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
> vaInitialize failed with error code -1 (unknown libva error),exit

So, I installed the latest Media SDK from here: (link) and installed latest version of LibVA

The output of vainfo now shows:
> error: XDG_RUNTIME_DIR not set in the environment.
> error: can't connect to X server!
> libva info: VA-API version 1.10.0
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> vaInitialize failed with error code -1 (unknown libva error),exit

Now I ran the stream the same way, that is feeding stream in loop (Start/Stop way). I have added an memory_profiler to my python code. I still see the memory keeps growing. If the cause is decodebin , I can try removing it, directly replacing it with qtdemux ! avdec_h264| will not work as in my case the source is not a file source but a stream coming from remote client using rtspclientsink=<rtsp://myserverurl:port/>

Could you suggest further ways to get to a solution for this memory growth issue?

Pulkit

**Comment by brmarkus** [comment] 2021-01-29 07:35
Regarding getting valid output of `vainfo` you need to set a few ENV variables, I think.
Depending on where the components were installed it could be something like this:

```
export LIBVA_DRIVERS_PATH=/opt/intel/openvino_2020.4.287/opt/intel/mediasdk/lib64
export MFX_HOME=/opt/intel/openvino_2020.4.287/opt/intel/mediasdk
export LIBVA_DRIVER_NAME=iHD
export LIBVA_LIB_DIR=/opt/intel/openvino_2020.4.287/opt/intel/mediasdk/lib64
```

**Comment by alekseyfa** [comment] 2021-01-29 17:54
@Pulkit0810 from your `vainfo` log I don't see that the ` iHD_drv_video.so` driver is specified. As @brmarkus mentioned, you need to set `LIBVA_DRIVERS_PATH` and `LIBVA_DRIVER_NAME` variables in your environment. Here the [link ](https://github.com/intel/media-driver/wiki/How-to-build-and-use-media-driver%3F#check-the-current-media-driver) with media-driver docs to help you validate environment.

For example how `vainfo` should be displayed with the specified variables:
```
libva info: VA-API version 1.8.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.8 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.2.0 (97e2ea9)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```

**Comment by mliu2020** [comment] 2021-02-01 23:02
Hi @Pulkit0810,

Did you confirm the media driver enabling mentioned by @brmarkus and @alekseyfa?

As @alekseyfa mentioned in this [post](https://github.com/openvinotoolkit/dlstreamer_gst/issues/172#issuecomment-764503040), dev team think the oversized memory is caused by the media driver. Your [previous post](https://github.com/openvinotoolkit/dlstreamer_gst/issues/172#issuecomment-769258510) shows the new driver was not enabled yet.

@brmarkus's comment assume specific release, so in general case you can do:
- Go to [Media SDK latest release](https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-20.5.1)
- Download tar ball MediaStack.tar.gz
- Untar and run "sudo install_media.sh"
- Run vainfo and you should get expected result showed as in @alekseyfa's comment.

If not, make sure you have the environment variables:
`export LIBVA_DRIVERS_PATH=/opt/intel/mediasdk/lib64
export MFX_HOME=/opt/intel/mediasdk
export LIBVA_DRIVER_NAME=iHD
export LIBVA_LIB_DIR=/opt/intel/mediasdk/lib64`

Let me know if you need any help on this.

Mark

**Comment by Pulkit0810** [comment] 2021-02-02 09:17
Hi @mliu2020 ,

As you said decodebin by default uses gst-vaapi. The accelerator that I am using at present is HDDL-R, does it require vaapi?  How does vainfo output look like when using HDDL-R card?

FYI, I am running the application in a Docker container, containing Openvino 2020.2. Running vainfo after the above steps (seeting environment variable and building iHD_drv_video.so gives me the following:
`
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.10.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri//iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /usr/lib/x86_64-linux-gnu/dri//iHD_drv_video.so init failed
libva info: va_openDriver() returns 18
vaInitialize failed with error code 18 (invalid parameter),exit

Pulkit

**Comment by Pulkit0810** [comment] 2021-02-02 12:54
Attaching  my usr/local/lib/x86_64-linux-gnu/dri snapshot.

![dri_content](https://user-images.githubusercontent.com/71756035/106603110-e6aab380-6583-11eb-9dce-0e033d507934.JPG)

**Comment by brmarkus** [comment] 2021-02-02 17:01
Do you have an Intel GPU in your system, multiple GPUs?
Have you started your Docker container with e.g. "--device /dev/dri:/dev/dri", which "maps" the i915 kernel-module's interface of the DirectRenderingInterface into the Docker container (which then allows applications within the container to access the GPU)?

Regarding X-server - do you have X/X11 running in your Host (outside of the container)?
I usually add "-e DISPLAY=${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix" to the Docker command line, requiring to set the ENV variable "DISPLAY".

**Comment by Pulkit0810** [comment] 2021-02-02 17:53
> Do you have an Intel GPU in your system, multiple GPUs?
> Have you started your Docker container with e.g. "--device /dev/dri:/dev/dri", which "maps" the i915 kernel-module's interface of the DirectRenderingInterface into the Docker container (which then allows applications within the container to access the GPU)?
> 
> Regarding X-server - do you have X/X11 running in your Host (outside of the container)?
> I usually add "-e DISPLAY=${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix" to the Docker command line, requiring to set the ENV variable "DISPLAY".

Hi @brmarkus ,

No, Its a bare metal CentOS machine with No intel GPUs. It has an HDDL-R card attached though. In the docker container we mount /var/tmp volume and also have intel-vpu-plugin configured in our K8s cluster where this container runs as a Pod. It is able to offload inference to HDDL (8 VPUs) via "device=HDDL" mentioned in our pipeline. But running one client after the other in a loop, increasing the memory usage and we have certain memory limits for the Pod, which causes OOM or pod termination. Thats the issue we are trying to get a solution of. But nothing has worked so far. 

Our RTSP Server and pipeline at based in python and we have all garbage collection in place, however it seems that somehow the pipelines are holding memory. even if we run 10 streams one after the other, and stop sending any further streams and all streams are stopped, the container is still holding the memory it used to run 10 streams one by one.

Pulkit

**Comment by brmarkus** [comment] 2021-02-02 20:00
Ah, ok, I see - without a GPU it doesn't make sense to consider libva for HW-accelerated video-decoding/encoding/processing... That explains why vainfo (via libva and the backend/media-driver) couldn't retrieve supported codec-details from a GPU.
There is no GPU at all in your system or a GPU from another vendor - for which then you would need a corresponding media-driver for libva and the corresponding vaapi-gstreamer plugin...

**Comment by mliu2020** [comment] 2021-02-02 22:30
Agree with @brmarkus, no sense for libVA.

@Pulkit0810, I think we are back to the original point with this new info. So I need some refresh:
- Which Intel processor are you using?
- Minimal CentOS installation.
- Are you using Docker image built by DL Streamer docker file?

When you described your scenario "When we run client in loop, where client connect one after the other, then it creates number of threads and these threads are probably holding memory which keeps on accumulating.
Within 30 minutes, the application consumes around 8GB."

So the clients was started one at a time, next client started after the previous client stopped, can you confirm?

Based on your configuration and the test scenario, we might think differently.

Mark

**Comment by Pulkit0810** [comment] 2021-02-03 11:33
Here is configuration:
[root@vcahost203 ~]# lscpu
Architecture:            86_64
CPU op-mode(s):     32-bit, 64-bit
Byte Order:              Little Endian
CPU(s):                     32
On-line CPU(s) list:  0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):                 1
NUMA node(s):       1
Vendor ID:               GenuineIntel
CPU family:              6
Model:                     85
Model name:           Intel(R) Xeon(R) D-2183IT CPU @ 2.20GHz
Stepping:                4
CPU MHz:               1622.070
CPU max MHz:        3000.0000
CPU min MHz:        1000.0000
BogoMIPS:              4400.00
Virtualization:          VT-x
L1d cache:              32K
L1i cache:               32K
L2 cache:                1024K
L3 cache:                22528K
NUMA node0 CPU(s):   0-31

Minimal CentOS installation.

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Are you using Docker image built by DL Streamer docker file?
Yes. 

the clients was started one at a time, next client started after the previous client stopped.
- Yes. this is correct

Also, from the recent findings, the memory growth issue is only scene when inference device (gvainference in one pipeline, gvadetect in other pipeline) used is HDDL.


Pulkit

**Comment by mliu2020** [comment] 2021-02-05 07:33
@Pulkit0810,

Thanks for the info. I will tell dev team this info and I am also trying a start/kill gst-launch for an hour in my local machine and see if I can reproduce.

Mark

**Comment by Pulkit0810** [comment] 2021-02-11 09:45
> @Pulkit0810,
> 
> Thanks for the info. I will tell dev team this info and I am also trying a start/kill gst-launch for an hour in my local machine and see if I can reproduce.
> 
> Mark

Do you have any update on this issue?


Pulkit

**Comment by mliu2020** [comment] 2021-02-12 00:41
Yes, and thanks for reminding.

I run the test several times and didn't observe significant free memory size changes. I used the report from `top` and Ubuntu system monitor.

dev team has started the investigation on this issue, I will keep you updated but don't hesitate to remind me for the updates.

Mark

**Comment by nprotasov** [comment] 2021-04-06 14:40
> Hello Team,
> 
> While connecting the client with the RTSP server, one RTSPMediaFactory instance is created and with the help of that instance, we set some properties like "set_transport_mode", "set_launch", "set_shared" and start the streaming for client to server.
> But after 10-11 hour, server get crash and showing out of memory.
> I have used 10GB memory,
> 
> > In the begning:
> > Memory: 1GB
> > After crash
> > Memory - 10GB
> 
> **Server**:
> 
> > server = GstRtspServer.RTSPServer.new()
> > factory = GstRtspServer.RTSPMediaFactory.new()
> > server.connect("client-connected", client_connected)
> > def client_connected(server, client):
> > factory.set_transport_mode(GstRtspServer.RTSPTransportMode.RECORD)
> > factory.set_launch(pipeline)
> > factory.set_shared(True)
> > mounts.add_factory("/traffic", factory)
> > pipeline="decodebin name=depay0 ! videoconvert ! gvafpscounter ! fakesink"
> 
> and this function (client_connected) always call when adding a new stream.
> @dsmertin , @mliu2020 , Can you please check where I am wrong!
> 
> Thanks
> Pulkit

Hello, sorry for late reply, we tried different scenarios, but we don't see any memory leaks. We suppose that we have different format of video stream. We want to understand in which elements the decodebin is expanded. So can you share your DOT files which generate your server?
Define the GST_DEBUG_DUMP_DOT_DIR environment variable with location for the generated pipeline graphs and run your server, receive few videos, stop server and send dot files to us.

**Comment by mliu2020** [comment] 2021-08-16 20:26
Hi, @Pulkit0810,

Since we don't receive any update since April, let me close it for now.

Feel free to open a new issue if you want to continue investigation.

Mark

**Closed by mliu2020** 2021-08-16 20:26 UTC
Labels: bug
