### ISSUE TITLE
YOLO + MULTI produce noisy roi

### ISSUE THREAD

**Issue by b04505009** [openvinotoolkit/dlstreamer_gst#207] opened 2021-04-16 09:01 UTC
When I use yolo-v4-tiny model for gvadetect, and set low threshold (0.3), I got many meaningless roi result, but this wasn't happened if I use CPU or GPU only.

My sample pipeline:
```
gst-launch-1.0 filesrc location=../test_videos/US.mp4 ! decodebin ! video/x-raw,format=NV12 ! \
gvadetect name=gvadetect device=MULTI:CPU,GPU inference-interval=1 model=../models/license_plate_recognition/yolov4-tiny-3l-alpr_416/FP32/yolov4-tiny-3l-alpr_416.xml model_proc=../models/license_plate_recognition/yolov4-tiny-3l-alpr_416/yolov4-tiny-3l-alpr.json pre-process-backend=opencv threshold=0.3 ! \
gvatrack name=gvatrack tracking-type=short-term ! gvawatermark ! \
queue ! videoconvert ! gvafpscounter ! fpsdisplaysink video-sink=xvimagesink sync=false
```
Screenshot:
![Screenshot from 2021-04-16 16-44-06](https://user-images.githubusercontent.com/14859904/114999919-dfcde480-9ed4-11eb-8192-a3dac89b8297.png)

[yolov4-tiny-3l-alpr_416.zip](https://github.com/openvinotoolkit/dlstreamer_gst/files/6323783/yolov4-tiny-3l-alpr_416.zip)

**Comment by mliu2020** [comment] 2021-04-16 21:04
@b04505009,

From your description, this issue relates to the detection error when using yolo-v4-tiny with hybrid mode. Since the result bounding box is only related to the accelerator mode, I doubt this is an inference engine issue.

If you remove the gvatrack and gvafpscount, do you get the same result? I want to remove gva element as less as possible and see the impact.

The other observation is, I can't find the yolo-v4-tiny model in [OMZ ](https://github.com/openvinotoolkit/open_model_zoo)repo, so I think OpenVINO doesn't support it yet.

Mark

Mark

**Comment by b04505009** [comment] 2021-04-19 01:43
Hi @mliu2020,

Thank you for your quick response. I removed gvafpscounter, and compared the result with or without gvatrack. This problem becomes less frequently if I remove gvatrack, but it still happens. You can check the result:

[track.mp4](https://drive.google.com/file/d/1bUAo6Xr1HWKbBFzDuWZ5tnVzsF3Kc_wm/view?usp=sharing)
[notrack.mp4](https://drive.google.com/file/d/1ygjvROZL2rrxXTZoTw_U6l1PYn88Xshu/view?usp=sharing)

I also tested the model with our modified version of [Security Barrier Camera C++ Demo](https://docs.openvinotoolkit.org/latest/omz_demos_security_barrier_camera_demo_cpp.html) on Windows, and it works fine. So I guess it may not be an inference engine issue.

b04505009

**Comment by mliu2020** [comment] 2021-04-20 05:46
Thanks @b04505009,

If this relates to gvatrack, could you switch 2 modes of gvatrack and see if there is any difference?

Mark

**Comment by mliu2020** [comment] 2021-04-20 15:44
Hi @b04505009,

In your pipeline, could you set the threshold value to 0.5 and see if the problem still happens?

I check Security Barrier Camera set threshold value to [0.5](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/security_barrier_camera_demo/cpp/security_barrier_camera_demo.hpp#L70).

Mark

**Comment by b04505009** [comment] 2021-04-21 03:39
Hi @mliu2020,

The tracking type doesn't make difference. I guess the noisy roi will just appear on one frame, but gvatrack will generate roi to track those roi, which makes it left on the display longer.

I have tested with threshold 0.5 in pipeline, and the problem doesn't happen.

But there are still some doubts:
1. The problem doesn't appear even I use threshold=0.3 when using single device.
2. I already use threshold 0.3 in Security Barrier Camera Demo, and it still acts normally.

Based on these reasons, I think multi device mode may still have some issues (maybe synchronization?)

b04505009

**Comment by adranit** [comment] 2021-04-23 05:19
Hi @b04505009 ,
May I know if OMZ sample is used with multi-device and threshold=0.3 then the issue is not reproduced?

Also I tried to understand what short-term tracking with inference-interval=1 is used for. My opinion is such configuration is useless. If detection is run for each frame it is enough to use zero-term tracker.

**Comment by mliu2020** [comment] 2021-05-18 21:08
Hi @b04505009,

Did you check the Security Barrier Camera Demo with threshold 0.3 and multi-device? I want to put some investigation on this. 

Also it would be helpful if you can share the test video?

Mark Liu

**Comment by b04505009** [comment] 2021-05-19 02:59
Hi @mliu2020 
Since we modified  the Security Barrier Camera Demo to make it supports yolov4tiny, I think I cannot reproduce this with official demo, and I cannot share my code. 

Here is the [video](https://drive.google.com/file/d/15ReMneEhFTOhJF2ehFRSubNeW8t_vtQ2/view?usp=sharing)

**Comment by mliu2020** [comment] 2021-05-19 04:15
Thanks so much,

Understood!

Did you try multi-device with threshold 0.3 and see if the issue still exist?

Since you can't share the code, can I use this video to reproduce in other Yolo model? This is critical if we want to debug.

Mark Liu

**Comment by b04505009** [comment] 2021-05-19 07:06
Hi @mliu2020 

Yes I've tried that, and it seems not related to the threshold. Modified Security Barrier Camera Demo  can run normally, but dl_streamer not. 

I've shared my model at the bottom of the original post, feel free to test on it :)

**Comment by alekseyfa** [comment] 2021-08-12 10:27
Hi @b04505009 

I have not reproduced your problem with the latest version of the OV package. However, the noisy ROIs are observed in the previous 2021.3 release. Could you run your sample with the [2021.4](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html) release and see if a similar issue is reproducible?

**Comment by b04505009** [comment] 2021-08-12 16:01
Hi @alekseyfa 

Sorry but for some reason, I'm no longer working on this task. Still thank you for your response.

**Comment by mliu2020** [comment] 2021-08-12 21:34
Thanks @b04505009,

If you are no long request this issue, could I close it?

Mark

**Closed** 2021-08-16 09:28 UTC
