### ISSUE TITLE
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin intitialization failed

### ISSUE THREAD

**Issue by devdastl** [openvinotoolkit/dlstreamer_gst#161] opened 2020-11-23 12:58 UTC
Hello Everyone, 
I am trying to run below pipeline in docker container "gst-video-analytics:latest" ([reference_link](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide#install-in-docker-image))  - 
`GST_DEBUG=3 gst-launch-1.0 -v filesrc location=video-examples/test.mp4 ! decodebin ! videoconvert ! video/x-raw,format=I420  ! gvadetect model=/root/intel_models/root/models/intel/person-vehicle-bike-detection-crossroad-0078/FP16/person-vehicle-bike-detection-crossroad-0078.xml device=MYRIAD ! fpsdisplaysink video-sink=fakesink sync=false async-handling=true`

and I am getting this error - 
```
ERROR: from element /GstPipeline:pipeline0/GstGvaDetect:gvadetect0: base_inference plugin intitialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(137): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaDetect:gvadetect0:
Failed to construct OpenVINOImageInference
        Failed to allocate graph: NC_ERROR

Execution ended after 0:00:16.944330724
```
While running the same pipeline but with device=CPU and changing model to FP32 I am getting desired output. 
I have also followed steps mentioned in this [issue](https://github.com/openvinotoolkit/dlstreamer_gst/issues/54) to connect NCS2 with the host(Ubuntu 18.04).

Please help me to understand how to resolve this issue.
Thanks in advance

**Comment by mliu2020** [comment] 2020-11-23 21:16
@devdastl,

Could you describe your hardware platform? Are you using NCS2 in a Docker environment?

If yes, you have to make sure NCS2 is enabled in the environment, could you do "lsusb" and post the output?

Mark

**Comment by devdastl** [comment] 2020-11-24 04:37
hello @mliu2020,
Yes I am using NCS2 with Docker environment. I got this output from "lsusb" command in my host environment - 
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 03f0:094a Hewlett-Packard Optical Mouse [672662-001]
Bus 001 Device 083: ID 03e7:2485
Bus 001 Device 003: ID 0424:2240 Standard Microsystems Corp.
Bus 001 Device 002: ID 413c:2107 Dell Computer Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root `hub`
```
I am running my docker image with this command - 
` docker run -it --privileged -v /dev:/dev --network=host -v ~/.Xauthority:/root/.Xauthority -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPL=$DISPLAY -e HTTP_PROXY=$HTTP_PROXY -e HTTPS_PROXY=$HTTPS_PROXY -e http_proxy=$http_proxy -e https_proxy=$https_proxy -v ~/gva/data/models/intel:/root/intelodels:ro -v ~/gva/data/models/common:/root/common_models:ro -e MODELS_PATH=/root/intel_models:/root/common_models -v ~/gva/data/video:/root/video-examples:r-e VIDEO_EXAMPLES_DIR=/root/video-examples gst-video-analytics:latest`

**Comment by mliu2020** [comment] 2020-11-24 07:07
@devdastl,

I can see NCS2 is enabled in host but there might be problem when you use it in Docker.

Please refer to the following OpenVINO docker image and see if you can get clues:
https://hub.docker.com/r/openvino/ubuntu18_dev

Mark

**Comment by mliu2020** [comment] 2020-11-24 15:36
@devdastl,

The other way to check NCS2 enabling is to check whether OpenVINO’s benchmark_app (or any other sample) works with MYRIAD device in docker environment.

If OpenVINO sample works but DL Streamer sample doesn't, we can check if there is an issue.

Mark

**Comment by devdastl** [comment] 2020-12-03 15:45
Hello @mliu2020,

I am really sorry for such a late replay. 
I tried running the sample application on OpenVino docker image "openvino/ubuntu18_dev:latest" but got this error - 

```
E: [global] [     23629] [Scheduler00Thr] dispatcherEventSend:53        Write failed (header) (err -1) | event XLINK_PING_REQ

E: [xLink] [     23629] [Scheduler00Thr] sendEvents:1027        Event sending failed
E: [global] [     24630] [interactive_fac] XLinkOpenStream:73   Got wrong package from device, error code = X_LINK_ERROR
E: [ncAPI] [     24630] [interactive_fac] ncDeviceOpen:1100     can't open deviceMonitor stream due to unknown error
E: [global] [     24630] [Scheduler00Thr] dispatcherEventSend:53        Write failed (header) (err -4) | event XLINK_CREATE_STREAM_REQ

E: [xLink] [     24630] [Scheduler00Thr] sendEvents:1027        Event sending failed
```
I tried the same sample application with CPU and it was working fine. Below is the sample application execution commad - 

1. For Myraid - 
`./interactive_face_detection_demo -i /home/openvino/head-pose-face-detection-female-and-male.mp4 -m /opt/intel/openvino_2021.1.110/deployment_tools/tools/model_downloader/intel/face-detection-adas-0001/FP16/face-detection-adas-0001.xml -d MYRIAD -no_show`

2. For CPU - 
```
./interactive_face_detection_demo -i /home/openvino/head-pose-face-detection-female-and-male.mp
4 -m /opt/intel/openvino_2021.1.110/deployment_tools/tools/model_downloader/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml -d CPU -no_show
```
3. Docker run commad- 
`docker run -u 0 -it --device-cgroup-rule='c 189:* rmw' -v /dev/bus/usb:/dev/bus/usb --rm openvino/ubuntu18_dev:latest`

Thanks a lot for the help

**Comment by mliu2020** [comment] 2020-12-04 00:43
Yes, this seems like a NCS2 installation/configuration error. I don't have much experience on this. But I don't know where the correct installation guide is.

I find the following page the most closest one I can think of:
https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_movidius_setup_guide.html

Let me know if this helps.

Mark

**Comment by mliu2020** [comment] 2020-12-07 07:00
@devdastl, 

I checked issue #54 and @umed mentioned NCS2 must use FP16, can you also double check if the same sample you failed in FP32 can run under FP16?

Mark

**Comment by mliu2020** [comment] 2020-12-21 23:18
Hi @devdastl,

I apologized for the late response. I was trying to find a NCS2 device so I can try and help you.

First correct my error in previous message, the docker image I referenced is **ubuntu18_data_dev**, "ubuntu18_dev" doesn't include GST dependencies so you can't run DL Streamer. Since the latest release of 2021.2, this image becomes "ubuntu18_data_dev:2021.1"

I can run the command in your original question in 2021.1 release successfully with following steps:

1. Install udev rule by following [this instruction](https://github.com/openvinotoolkit/dlstreamer_gst/issues/54#issuecomment-608529488).
2. Insert NCS2 and confirm with `lsusb` command, I got the output exactly like you did.
3. Download the docker image: `docker pull  openvino/ubuntu18_data_dev:2021.1`
4. Run pipeline on host with command `gst-launch-1.0 filesrc location=<path to test.mp4> ! decodebin ! videoconvert ! video/x-raw,format=I420 ! gvadetect model=<path to model> device=MYRIAD batch-size=1 ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=fakesink sync=false`
5. Run this docker command `docker run -it --privileged -v /dev:/dev -v <My Video Directory>:/home/openvino/Downloads -v <My Model Directory>:/home/openvino/intel --network=host --rm openvino/ubuntu18_data_dev:2021.1`
6. Run this command `gst-launch-1.0 filesrc location=/home/openvino/Downloads/test.mp4 ! decodebin ! videoconvert ! video/x-raw,format=I420 ! gvadetect model=/home/openvino/intel/dl_streamer/models/intel/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.xml device=MYRIAD batch-size=1 ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=fakesink sync=false`

I also confirmed both FP16 and FP32 models running successfully.

Let me know if this solves your problem.

Mark

**Comment by mliu2020** [comment] 2021-02-15 23:59
Hi @devdastl,

I didn't get your respond, was the issue solved?

Let me know if you need more help or I can close this issue in a few days.

Mark Liu

**Comment by mliu2020** [comment] 2021-03-07 07:58
@devdastl ,

Let me close it for now and please feel free to reopen or submit a new issue.

Mark

**Closed by mliu2020** 2021-03-07 07:58 UTC
